package com.mohamad4444.github;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 * Abstract base class for generated database entity classes.
 * 
 * <p>
 * This class serves as the parent for all classes generated by the
 * {@link DbEntity}
 * annotation processor. Generated classes extend this base class and implement
 * the
 * {@link #buildDTO(ResultSet)} method to map database rows to DTO instances.
 * 
 * <p>
 * The class provides placeholder methods for common database operations like
 * query execution, single row retrieval, and updates. These methods should be
 * implemented based on your specific data access requirements.
 * 
 * <p>
 * <b>Example Usage:</b>
 * 
 * <pre>{@code
 * // Generated class
 * public class UserDTODB extends AbstractDB<UserDTO> { @Override
 *     protected UserDTO buildDTO(ResultSet rs) throws SQLException {
 *         return new UserDTO(rs.getInt("id"), rs.getString("username"));
 *     }
 * }
 * 
 * // Usage in application
 * UserDTODB userDb = new UserDTODB();
 * List<UserDTO> users = userDb.executeQuery(connection, "SELECT * FROM users");
 * }</pre>
 * 
 * @param <T> the DTO type this class maps to
 * @see DbEntity
 * @see DbField
 */
public abstract class AbstractDB<T> {

    /**
     * Builds a DTO instance from a ResultSet row.
     * 
     * <p>
     * This method must be implemented by generated subclasses to map a single
     * database row to a DTO instance. The implementation should extract values
     * from the ResultSet and pass them to the DTO constructor.
     * 
     * <p>
     * <b>Note:</b> This method should not advance the ResultSet cursor. It
     * should only read data from the current row.
     * 
     * @param rs the ResultSet positioned at the row to map
     * @return a new DTO instance populated with data from the ResultSet
     * @throws SQLException if a database access error occurs
     */
    protected abstract T buildDTO(ResultSet rs) throws SQLException;

    /**
     * Executes a query and returns a list of DTOs.
     * 
     * <p>
     * <b>Implementation Note:</b> This is a placeholder method. You should
     * implement this method to:
     * <ol>
     * <li>Prepare and execute the SQL statement with the provided parameters</li>
     * <li>Iterate through the ResultSet</li>
     * <li>Call {@link #buildDTO(ResultSet)} for each row</li>
     * <li>Collect results into a List</li>
     * </ol>
     * 
     * @param cn     the database connection
     * @param sql    the SQL query to execute
     * @param params optional query parameters for prepared statement
     * @return a list of DTOs, or {@code null} if not implemented
     */
    protected List<T> executeQuery(Connection cn, String sql, Object... params) {
        // Implement query execution logic
        return null; // Placeholder
    }

    /**
     * Executes a query and returns a single DTO.
     * 
     * <p>
     * <b>Implementation Note:</b> This is a placeholder method. You should
     * implement this method to:
     * <ol>
     * <li>Prepare and execute the SQL statement with the provided parameters</li>
     * <li>Get the first row from the ResultSet</li>
     * <li>Call {@link #buildDTO(ResultSet)} to map the row</li>
     * <li>Return the result or {@code null} if no rows found</li>
     * </ol>
     * 
     * @param cn     the database connection
     * @param sql    the SQL query to execute (should return at most one row)
     * @param params optional query parameters for prepared statement
     * @return a single DTO instance, or {@code null} if no rows found or not
     *         implemented
     */
    protected T executeSingleQuery(Connection cn, String sql, Object... params) {
        // Implement single row query logic
        return null; // Placeholder
    }

    /**
     * Executes an update, insert, or delete operation.
     * 
     * <p>
     * <b>Implementation Note:</b> This is a placeholder method. You should
     * implement this method to:
     * <ol>
     * <li>Prepare and execute the SQL statement with the provided parameters</li>
     * <li>Return the number of affected rows</li>
     * </ol>
     * 
     * @param cn     the database connection
     * @param sql    the SQL update/insert/delete statement to execute
     * @param params optional statement parameters for prepared statement
     * @return the number of rows affected, or 0 if not implemented
     */
    protected int executeUpdate(Connection cn, String sql, Object... params) {
        // Implement update/insert/delete operation
        return 0; // Placeholder
    }
}
